In [1]:
# importing required libraries
import numpy as np
import pandas as pd
import pickle # saving and loading trained model
from os import path

# importing required libraries for normalizing data
from sklearn import preprocessing
from sklearn.preprocessing import (StandardScaler, OrdinalEncoder,LabelEncoder, MinMaxScaler, OneHotEncoder)
from sklearn.preprocessing import Normalizer, MaxAbsScaler , RobustScaler, PowerTransformer

# importing library for plotting/

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import metrics
from sklearn.metrics import accuracy_score # for calculating accuracy of model
from sklearn.model_selection import train_test_split # for splitting the dataset for training and testing
from sklearn.metrics import classification_report # for generating a classification report of model

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve, auc

import tensorflow as tf
from tensorflow.keras.utils import to_categorical

from keras.layers import Dense # importing dense layer

from keras.layers import Input
from keras.models import Model
# representation of model layers
from keras.utils import plot_model
from sklearn.metrics import confusion_matrix
import shap
from imblearn.over_sampling import SMOTE
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer


/opt/homebrew/lib/python3.10/site-packages/shap/utils/_clustering.py:35: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def _pt_shuffle_rec(i, indexes, index_mask, partition_tree, M, pos):
/opt/homebrew/lib/python3.10/site-packages/shap/utils/_clustering.py:54: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def delta_minimization_order(all_masks, max_swap_size=100

In [2]:
#Defining metric functions
def ACC(TP,TN,FP,FN):
    Acc = (TP+TN)/(TP+FP+FN+TN)
    return Acc
def ACC_2 (TP, FN):
    ac = (TP/(TP+FN))
    return ac
def PRECISION(TP,FP):
    eps = 1e-7
    Precision = TP/(TP+FP+eps)
    

    return Precision
def RECALL(TP,FN):
    Recall = TP/(TP+FN)
    return Recall
def F1(Recall, Precision):
    F1 = 2 * Recall * Precision / (Recall + Precision)
    return F1
def BACC(TP,TN,FP,FN):
    BACC =(TP/(TP+FN)+ TN/(TN+FP))*0.5
    return BACC
def MCC(TP,TN,FP,FN):
    eps = 1e-7
    MCC = (TN*TP-FN*FP)/(((TP+FP+eps)*(TP+FN+eps)*(TN+FP+eps)*(TN+FN+eps))**.5)
    return MCC
def AUC_ROC(y_test_bin,y_score):
    fpr = dict()
    tpr = dict()
    roc_auc = dict()
    auc_avg = 0
    counting = 0
    for i in range(n_classes):
      fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_score[:, i])
     # plt.plot(fpr[i], tpr[i], color='darkorange', lw=2)
      #print('AUC for Class {}: {}'.format(i+1, auc(fpr[i], tpr[i])))
      auc_avg += auc(fpr[i], tpr[i])
      counting = i+1
    return auc_avg/counting

In [3]:
# attach the column names to the dataset
feature=["duration","protocol_type","service","flag","src_bytes","dst_bytes","land","wrong_fragment","urgent","hot",
          "num_failed_logins","logged_in","num_compromised","root_shell","su_attempted","num_root","num_file_creations","num_shells",
          "num_access_files","num_outbound_cmds","is_host_login","is_guest_login","count","srv_count","serror_rate","srv_serror_rate",
          "rerror_rate","srv_rerror_rate","same_srv_rate","diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count", 
          "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate","dst_host_srv_diff_host_rate","dst_host_serror_rate",
          "dst_host_srv_serror_rate","dst_host_rerror_rate","dst_host_srv_rerror_rate","label","difficulty"]
# KDDTrain+_2.csv & KDDTest+_2.csv are the datafiles without the last column about the difficulty score
# these have already been removed.

train='KDDTrain+.txt'
test='KDDTest+.txt'

df=pd.read_csv(train,names=feature)
df_test=pd.read_csv(test,names=feature)

# shape, this gives the dimensions of the dataset
print('Dimensions of the Training set:',df.shape)
print('Dimensions of the Test set:',df_test.shape)

Dimensions of the Training set: (125973, 43)
Dimensions of the Test set: (22544, 43)


In [4]:
df.drop(['difficulty'],axis=1,inplace=True)
df_test.drop(['difficulty'],axis=1,inplace=True)

In [5]:
print('Label distribution Training set:')
print(df['label'].value_counts())
print()
print('Label distribution Test set:')
print(df_test['label'].value_counts())

Label distribution Training set:
normal             67343
neptune            41214
satan               3633
ipsweep             3599
portsweep           2931
smurf               2646
nmap                1493
back                 956
teardrop             892
warezclient          890
pod                  201
guess_passwd          53
buffer_overflow       30
warezmaster           20
land                  18
imap                  11
rootkit               10
loadmodule             9
ftp_write              8
multihop               7
phf                    4
perl                   3
spy                    2
Name: label, dtype: int64

Label distribution Test set:
normal             9711
neptune            4657
guess_passwd       1231
mscan               996
warezmaster         944
apache2             737
satan               735
processtable        685
smurf               665
back                359
snmpguess           331
saint               319
mailbomb            293
snmpgetattack       178


In [6]:
# colums that are categorical and not binary yet: protocol_type (column 2), service (column 3), flag (column 4).
# explore categorical features
print('Training set:')
for col_name in df.columns:
    if df[col_name].dtypes == 'object' :
        unique_cat = len(df[col_name].unique())
        print("Feature '{col_name}' has {unique_cat} categories".format(col_name=col_name, unique_cat=unique_cat))

#see how distributed the feature service is, it is evenly distributed and therefore we need to make dummies for all.
print()
print('Distribution of categories in service:')
print(df['service'].value_counts().sort_values(ascending=False).head())

Training set:
Feature 'protocol_type' has 3 categories
Feature 'service' has 70 categories
Feature 'flag' has 11 categories
Feature 'label' has 23 categories

Distribution of categories in service:
http        40338
private     21853
domain_u     9043
smtp         7313
ftp_data     6860
Name: service, dtype: int64


In [7]:
# Test set
print('Test set:')
for col_name in df_test.columns:
    if df_test[col_name].dtypes == 'object' :
        unique_cat = len(df_test[col_name].unique())
        print("Feature '{col_name}' has {unique_cat} categories".format(col_name=col_name, unique_cat=unique_cat))

Test set:
Feature 'protocol_type' has 3 categories
Feature 'service' has 64 categories
Feature 'flag' has 11 categories
Feature 'label' has 38 categories


In [8]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
categorical_columns=['protocol_type', 'service', 'flag']
# insert code to get a list of categorical columns into a variable, categorical_columns
categorical_columns=['protocol_type', 'service', 'flag'] 
 # Get the categorical values into a 2D numpy array
df_categorical_values = df[categorical_columns]
testdf_categorical_values = df_test[categorical_columns]
df_categorical_values.head()

protocol_type   service flag
0           tcp  ftp_data   SF
1           udp     other   SF
2           tcp   private   S0
3           tcp      http   SF
4           tcp      http   SF

In [9]:
# protocol type
unique_protocol=sorted(df.protocol_type.unique())
string1 = 'Protocol_type_'
unique_protocol2=[string1 + x for x in unique_protocol]
# service
unique_service=sorted(df.service.unique())
string2 = 'service_'
unique_service2=[string2 + x for x in unique_service]
# flag
unique_flag=sorted(df.flag.unique())
string3 = 'flag_'
unique_flag2=[string3 + x for x in unique_flag]
# put together
dumcols=unique_protocol2 + unique_service2 + unique_flag2
print(dumcols)

#do same for test set
unique_service_test=sorted(df_test.service.unique())
unique_service2_test=[string2 + x for x in unique_service_test]
testdumcols=unique_protocol2 + unique_service2_test + unique_flag2

['Protocol_type_icmp', 'Protocol_type_tcp', 'Protocol_type_udp', 'service_IRC', 'service_X11', 'service_Z39_50', 'service_aol', 'service_auth', 'service_bgp', 'service_courier', 'service_csnet_ns', 'service_ctf', 'service_daytime', 'service_discard', 'service_domain', 'service_domain_u', 'service_echo', 'service_eco_i', 'service_ecr_i', 'service_efs', 'service_exec', 'service_finger', 'service_ftp', 'service_ftp_data', 'service_gopher', 'service_harvest', 'service_hostnames', 'service_http', 'service_http_2784', 'service_http_443', 'service_http_8001', 'service_imap4', 'service_iso_tsap', 'service_klogin', 'service_kshell', 'service_ldap', 'service_link', 'service_login', 'service_mtp', 'service_name', 'service_netbios_dgm', 'service_netbios_ns', 'service_netbios_ssn', 'service_netstat', 'service_nnsp', 'service_nntp', 'service_ntp_u', 'service_other', 'service_pm_dump', 'service_pop_2', 'service_pop_3', 'service_printer', 'service_private', 'service_red_i', 'service_remote_job', 'serv

In [10]:
df_categorical_values_enc=df_categorical_values.apply(LabelEncoder().fit_transform)
print(df_categorical_values_enc.head())
# test set
testdf_categorical_values_enc=testdf_categorical_values.apply(LabelEncoder().fit_transform)

   protocol_type  service  flag
0              1       20     9
1              2       44     9
2              1       49     5
3              1       24     9
4              1       24     9


In [11]:
enc = OneHotEncoder()
df_categorical_values_encenc = enc.fit_transform(df_categorical_values_enc)
df_cat_data = pd.DataFrame(df_categorical_values_encenc.toarray(),columns=dumcols)
# test set
testdf_categorical_values_encenc = enc.fit_transform(testdf_categorical_values_enc)
testdf_cat_data = pd.DataFrame(testdf_categorical_values_encenc.toarray(),columns=testdumcols)

df_cat_data.head()

Protocol_type_icmp  Protocol_type_tcp  Protocol_type_udp  service_IRC  \
0                 0.0                1.0                0.0          0.0   
1                 0.0                0.0                1.0          0.0   
2                 0.0                1.0                0.0          0.0   
3                 0.0                1.0                0.0          0.0   
4                 0.0                1.0                0.0          0.0   

   service_X11  service_Z39_50  service_aol  service_auth  service_bgp  \
0          0.0             0.0          0.0           0.0          0.0   
1          0.0             0.0          0.0           0.0          0.0   
2          0.0             0.0          0.0           0.0          0.0   
3          0.0             0.0          0.0           0.0          0.0   
4          0.0             0.0          0.0           0.0          0.0   

   service_courier  ...  flag_REJ  flag_RSTO  flag_RSTOS0  flag_RSTR  flag_S0  \
0              0.0  ...       0.0        0.0          0.0        0.0      0.0   
1              0.0  ...       0.0        0.0          0.0        0.0      0.0   
2              0.0  ...       0.0        0.0          0.0        0.0      1.0   
3              0.0  ...       0.0        0.0          0.0        0.0      0.0   
4              0.0  ...       0.0        0.0          0.0        0.0      0.0   

   flag_S1  flag_S2  flag_S3  flag_SF  flag_SH  
0      0.0      0.0      0.0      1.0      0.0  
1      0.0      0.0      0.0      1.0      0.0  
2      0.0      0.0      0.0      0.0      0.0  
3      0.0      0.0      0.0      1.0      0.0  
4      0.0      0.0      0.0      1.0      0.0  

[5 rows x 84 columns]

In [12]:
trainservice=df['service'].tolist()
testservice= df_test['service'].tolist()
difference=list(set(trainservice) - set(testservice))
string = 'service_'
difference=[string + x for x in difference]
difference

['service_urh_i',
 'service_http_8001',
 'service_aol',
 'service_red_i',
 'service_harvest',
 'service_http_2784']

In [13]:
for col in difference:
    testdf_cat_data[col] = 0

testdf_cat_data.shape

(22544, 84)

In [14]:
newdf=df.join(df_cat_data)
newdf.drop('flag', axis=1, inplace=True)
newdf.drop('protocol_type', axis=1, inplace=True)
newdf.drop('service', axis=1, inplace=True)
# test data
newdf_test=df_test.join(testdf_cat_data)
newdf_test.drop('flag', axis=1, inplace=True)
newdf_test.drop('protocol_type', axis=1, inplace=True)
newdf_test.drop('service', axis=1, inplace=True)
print(newdf.shape)
print(newdf_test.shape)

(125973, 123)
(22544, 123)


In [15]:
# take label column
labeldf=newdf['label']
labeldf_test=newdf_test['label']
# change the label column
newlabeldf=labeldf.replace({ 'normal' : 0, 'neptune' : 1 ,'back': 1, 'land': 1, 'pod': 1, 'smurf': 1, 'teardrop': 1,'mailbomb': 1, 'apache2': 1, 'processtable': 1, 'udpstorm': 1, 'worm': 1,
                           'ipsweep' : 2,'nmap' : 2,'portsweep' : 2,'satan' : 2,'mscan' : 2,'saint' : 2
                           ,'ftp_write': 3,'guess_passwd': 3,'imap': 3,'multihop': 3,'phf': 3,'spy': 3,'warezclient': 3,'warezmaster': 3,'sendmail': 3,'named': 3,'snmpgetattack': 3,'snmpguess': 3,'xlock': 3,'xsnoop': 3,'httptunnel': 3,
                           'buffer_overflow': 4,'loadmodule': 4,'perl': 4,'rootkit': 4,'ps': 4,'sqlattack': 4,'xterm': 4})
newlabeldf_test=labeldf_test.replace({ 'normal' : 0, 'neptune' : 1 ,'back': 1, 'land': 1, 'pod': 1, 'smurf': 1, 'teardrop': 1,'mailbomb': 1, 'apache2': 1, 'processtable': 1, 'udpstorm': 1, 'worm': 1,
                           'ipsweep' : 2,'nmap' : 2,'portsweep' : 2,'satan' : 2,'mscan' : 2,'saint' : 2
                           ,'ftp_write': 3,'guess_passwd': 3,'imap': 3,'multihop': 3,'phf': 3,'spy': 3,'warezclient': 3,'warezmaster': 3,'sendmail': 3,'named': 3,'snmpgetattack': 3,'snmpguess': 3,'xlock': 3,'xsnoop': 3,'httptunnel': 3,
                           'buffer_overflow': 4,'loadmodule': 4,'perl': 4,'rootkit': 4,'ps': 4,'sqlattack': 4,'xterm': 4})
# put the new label column back
newdf['label'] = newlabeldf
newdf_test['label'] = newlabeldf_test
print(newdf['label'].head())

0    0
1    0
2    1
3    0
4    0
Name: label, dtype: int64


In [16]:
# creating a dataframe with multi-class labels (Dos,Probe,R2L,U2R,normal)
multi_data = newdf.copy()
multi_label = pd.DataFrame(multi_data.label)

multi_data_test=newdf_test.copy()
multi_label_test = pd.DataFrame(multi_data_test.label)

In [17]:
# using standard scaler for normalizing
std_scaler = StandardScaler()
def standardization(df,col):
    for i in col:
        arr = df[i]
        arr = np.array(arr)
        df[i] = std_scaler.fit_transform(arr.reshape(len(arr),1))
    return df

numeric_col = multi_data.select_dtypes(include='number').columns
data = standardization(multi_data,numeric_col)
numeric_col_test = multi_data_test.select_dtypes(include='number').columns
data_test = standardization(multi_data_test,numeric_col_test)

In [18]:
# label encoding (0,1,2,3,4) multi-class labels (Dos,normal,Probe,R2L,U2R)
le2 = preprocessing.LabelEncoder()
le2_test = preprocessing.LabelEncoder()
enc_label = multi_label.apply(le2.fit_transform)
enc_label_test = multi_label_test.apply(le2_test.fit_transform)
multi_data = multi_data.copy()
multi_data_test = multi_data_test.copy()

multi_data['intrusion'] = enc_label
multi_data_test['intrusion'] = enc_label_test

#y_mul = multi_data['intrusion']
multi_data
multi_data_test


duration  src_bytes  dst_bytes      land  wrong_fragment    urgent  \
0     -0.155534  -0.021988  -0.096896 -0.017624       -0.059104 -0.019459   
1     -0.155534  -0.021988  -0.096896 -0.017624       -0.059104 -0.019459   
2     -0.154113   0.005473  -0.096896 -0.017624       -0.059104 -0.019459   
3     -0.155534  -0.021946  -0.096896 -0.017624       -0.059104 -0.019459   
4     -0.154823  -0.021988  -0.096189 -0.017624       -0.059104 -0.019459   
...         ...        ...        ...       ...             ...       ...   
22539 -0.155534  -0.020309  -0.081202 -0.017624       -0.059104 -0.019459   
22540 -0.155534  -0.021318  -0.052690 -0.017624       -0.059104 -0.019459   
22541 -0.155534   0.093373   0.294926 -0.017624       -0.059104 -0.019459   
22542 -0.155534  -0.021899  -0.094917 -0.017624       -0.059104 -0.019459   
22543 -0.155534  -0.021988  -0.096896 -0.017624       -0.059104 -0.019459   

            hot  num_failed_logins  logged_in  num_compromised  ...   flag_S3  \
0     -0.113521          -0.143999  -0.890373        -0.016494  ... -0.105681   
1     -0.113521          -0.143999  -0.890373        -0.016494  ... -0.105681   
2     -0.113521          -0.143999  -0.890373        -0.016494  ... -0.105681   
3     -0.113521          -0.143999  -0.890373        -0.016494  ... -0.105681   
4     -0.113521          -0.143999  -0.890373        -0.016494  ... -0.105681   
...         ...                ...        ...              ...  ...       ...   
22539 -0.113521          -0.143999   1.123125        -0.016494  ... -0.105681   
22540 -0.113521          -0.143999   1.123125        -0.016494  ... -0.105681   
22541  2.040705          -0.143999   1.123125         0.121069  ... -0.105681   
22542 -0.113521          -0.143999  -0.890373        -0.016494  ... -0.105681   
22543 -0.113521          -0.143999  -0.890373        -0.016494  ... -0.105681   

        flag_SF   flag_SH  service_http_8001  service_http_2784  service_aol  \
0     -1.392705 -0.056997                0.0                0.0          0.0   
1     -1.392705 -0.056997                0.0                0.0          0.0   
2      0.718027 -0.056997                0.0                0.0          0.0   
3      0.718027 -0.056997                0.0                0.0          0.0   
4     -1.392705 -0.056997                0.0                0.0          0.0   
...         ...       ...                ...                ...          ...   
22539  0.718027 -0.056997                0.0                0.0          0.0   
22540  0.718027 -0.056997                0.0                0.0          0.0   
22541  0.718027 -0.056997                0.0                0.0          0.0   
22542  0.718027 -0.056997                0.0                0.0          0.0   
22543 -1.392705 -0.056997                0.0                0.0          0.0   

       service_harvest  service_red_i  service_urh_i  intrusion  
0                  0.0            0.0            0.0          1  
1                  0.0            0.0            0.0          1  
2                  0.0            0.0            0.0          0  
3                  0.0            0.0            0.0          2  
4                  0.0            0.0            0.0          2  
...                ...            ...            ...        ...  
22539              0.0            0.0            0.0          0  
22540              0.0            0.0            0.0          0  
22541              0.0            0.0            0.0          1  
22542              0.0            0.0            0.0          0  
22543              0.0            0.0            0.0          2  

[22544 rows x 124 columns]

In [19]:

multi_data.drop(labels= [ 'label'], axis=1, inplace=True)
multi_data
multi_data_test.drop(labels= [ 'label'], axis=1, inplace=True)
multi_data_test

duration  src_bytes  dst_bytes      land  wrong_fragment    urgent  \
0     -0.155534  -0.021988  -0.096896 -0.017624       -0.059104 -0.019459   
1     -0.155534  -0.021988  -0.096896 -0.017624       -0.059104 -0.019459   
2     -0.154113   0.005473  -0.096896 -0.017624       -0.059104 -0.019459   
3     -0.155534  -0.021946  -0.096896 -0.017624       -0.059104 -0.019459   
4     -0.154823  -0.021988  -0.096189 -0.017624       -0.059104 -0.019459   
...         ...        ...        ...       ...             ...       ...   
22539 -0.155534  -0.020309  -0.081202 -0.017624       -0.059104 -0.019459   
22540 -0.155534  -0.021318  -0.052690 -0.017624       -0.059104 -0.019459   
22541 -0.155534   0.093373   0.294926 -0.017624       -0.059104 -0.019459   
22542 -0.155534  -0.021899  -0.094917 -0.017624       -0.059104 -0.019459   
22543 -0.155534  -0.021988  -0.096896 -0.017624       -0.059104 -0.019459   

            hot  num_failed_logins  logged_in  num_compromised  ...   flag_S3  \
0     -0.113521          -0.143999  -0.890373        -0.016494  ... -0.105681   
1     -0.113521          -0.143999  -0.890373        -0.016494  ... -0.105681   
2     -0.113521          -0.143999  -0.890373        -0.016494  ... -0.105681   
3     -0.113521          -0.143999  -0.890373        -0.016494  ... -0.105681   
4     -0.113521          -0.143999  -0.890373        -0.016494  ... -0.105681   
...         ...                ...        ...              ...  ...       ...   
22539 -0.113521          -0.143999   1.123125        -0.016494  ... -0.105681   
22540 -0.113521          -0.143999   1.123125        -0.016494  ... -0.105681   
22541  2.040705          -0.143999   1.123125         0.121069  ... -0.105681   
22542 -0.113521          -0.143999  -0.890373        -0.016494  ... -0.105681   
22543 -0.113521          -0.143999  -0.890373        -0.016494  ... -0.105681   

        flag_SF   flag_SH  service_http_8001  service_http_2784  service_aol  \
0     -1.392705 -0.056997                0.0                0.0          0.0   
1     -1.392705 -0.056997                0.0                0.0          0.0   
2      0.718027 -0.056997                0.0                0.0          0.0   
3      0.718027 -0.056997                0.0                0.0          0.0   
4     -1.392705 -0.056997                0.0                0.0          0.0   
...         ...       ...                ...                ...          ...   
22539  0.718027 -0.056997                0.0                0.0          0.0   
22540  0.718027 -0.056997                0.0                0.0          0.0   
22541  0.718027 -0.056997                0.0                0.0          0.0   
22542  0.718027 -0.056997                0.0                0.0          0.0   
22543 -1.392705 -0.056997                0.0                0.0          0.0   

       service_harvest  service_red_i  service_urh_i  intrusion  
0                  0.0            0.0            0.0          1  
1                  0.0            0.0            0.0          1  
2                  0.0            0.0            0.0          0  
3                  0.0            0.0            0.0          2  
4                  0.0            0.0            0.0          2  
...                ...            ...            ...        ...  
22539              0.0            0.0            0.0          0  
22540              0.0            0.0            0.0          0  
22541              0.0            0.0            0.0          1  
22542              0.0            0.0            0.0          0  
22543              0.0            0.0            0.0          2  

[22544 rows x 123 columns]

In [20]:
y_train_multi= multi_data[['intrusion']]
X_train_multi= multi_data.drop(labels=['intrusion'], axis=1)

print('X_train has shape:',X_train_multi.shape,'\ny_train has shape:',y_train_multi.shape)

y_test_multi= multi_data_test[['intrusion']]
X_test_multi= multi_data_test.drop(labels=['intrusion'], axis=1)

print('X_test has shape:',X_test_multi.shape,'\ny_test has shape:',y_test_multi.shape)

X_train has shape: (125973, 122) 
y_train has shape: (125973, 1)
X_test has shape: (22544, 122) 
y_test has shape: (22544, 1)


In [21]:
from sklearn.preprocessing import LabelBinarizer

y_train_multi = LabelBinarizer().fit_transform(y_train_multi)
y_train_multi

y_test_multi = LabelBinarizer().fit_transform(y_test_multi)
y_test_multi

array([[0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       ...,
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [22]:
Y_train=y_train_multi.copy()
X_train=X_train_multi.copy()

Y_test=y_test_multi.copy()
X_test=X_test_multi.copy()

In [23]:
from sklearn.preprocessing import MinMaxScaler

# Create a MinMaxScaler object
scaler = MinMaxScaler()

# Fit the scaler to the training data and transform it in one step
X_train_n = scaler.fit_transform(X_train)

# Transform the test data using the fitted scaler
X_test_n = scaler.transform(X_test)

# Print the transformed data
print(X_train)
print(X_test)


        duration  src_bytes  dst_bytes      land  wrong_fragment    urgent  \
0      -0.110249  -0.007679  -0.004919 -0.014089       -0.089486 -0.007736   
1      -0.110249  -0.007737  -0.004919 -0.014089       -0.089486 -0.007736   
2      -0.110249  -0.007762  -0.004919 -0.014089       -0.089486 -0.007736   
3      -0.110249  -0.007723  -0.002891 -0.014089       -0.089486 -0.007736   
4      -0.110249  -0.007728  -0.004814 -0.014089       -0.089486 -0.007736   
...          ...        ...        ...       ...             ...       ...   
125968 -0.110249  -0.007762  -0.004919 -0.014089       -0.089486 -0.007736   
125969 -0.107178  -0.007744  -0.004883 -0.014089       -0.089486 -0.007736   
125970 -0.110249  -0.007382  -0.004823 -0.014089       -0.089486 -0.007736   
125971 -0.110249  -0.007762  -0.004919 -0.014089       -0.089486 -0.007736   
125972 -0.110249  -0.007737  -0.004919 -0.014089       -0.089486 -0.007736   

             hot  num_failed_logins  logged_in  num_compromised

The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.



In [24]:
import pandas as pd

# Convert normalized data back to DataFrame
X_train = pd.DataFrame(X_train_n, columns=X_train.columns)
X_test = pd.DataFrame(X_test_n, columns=X_test.columns)


In [25]:
# Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
import time

# Create a RandomForestClassifier instance
rf = RandomForestClassifier(n_estimators=100, max_depth=10, min_samples_split=5,
                            min_samples_leaf=3, class_weight='balanced_subsample',
                            random_state=0)

# Record the start time
start = time.time()
y_train_single_column = np.argmax(Y_train, axis=1)

# Train the classifier
rf.fit(X_train, y_train_single_column)  # Assuming y_train_single_column is your target with single column containing class labels

# Record the end time
end = time.time()

# Print the time taken for training
print(f'Time taken for training: {end - start} seconds')

# Predict the classes and the class probabilities of the test set
y_preds = rf.predict(X_test)
y_probs = rf.predict_proba(X_test)

# Print the predictions and probabilities
print(y_preds)
print(y_probs)


Time taken for training: 6.393641233444214 seconds


The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.



[2 2 0 ... 0 0 2]
[[0.24784092 0.25829828 0.45914823 0.02526427 0.00944829]
 [0.23259453 0.22173255 0.50401323 0.02313337 0.01852634]
 [0.54058265 0.06596204 0.21344676 0.14363959 0.03636896]
 ...
 [0.60006682 0.27243446 0.02493576 0.07279594 0.02976702]
 [0.74340328 0.09869544 0.11259999 0.03173131 0.01356998]
 [0.30394399 0.14108484 0.51662034 0.02606299 0.01228785]]


In [26]:
y_test_single_column = np.argmax(Y_test, axis=1)

In [38]:
Probe_sample = X_test.iloc[0].values

In [126]:
import warnings
warnings.filterwarnings("ignore")

In [40]:
import lime
from lime.lime_tabular import LimeTabularExplainer 
import numpy as np

# Wrapping the predict_proba method to ensure it returns a 2D numpy array
def predict_proba(instance):
    probs = np.array(rf.predict_proba(instance))
    print(f"Original shape of probs: {probs.shape}")  
    
    # Averaging the probabilities across the first dimension
    if len(probs.shape) == 3:
        probs = np.mean(probs, axis=0)
        
    print(f"Modified shape of probs: {probs.shape}")  
    return probs


# Creating the explainer with the training data, feature names, and class names
explainer = LimeTabularExplainer(X_test.values,
                                 feature_names=X_train.columns.tolist(),
                                 class_names=['Normal', 'DoS', 'Probe', 'U2R', 'R2L'])

# Getting a specific instance from the test data
instance = X_test.iloc[0].values

# Generating the explanation for the instance
exp = explainer.explain_instance(Probe_sample, 
                                 predict_proba,  # Using the wrapped function
                                 num_features=7, 
                                 top_labels=1)

# Displaying the explanation



X does not have valid feature names, but RandomForestClassifier was fitted with feature names


Original shape of probs: (5000, 5)
Modified shape of probs: (5000, 5)


In [ ]:
exp.show_in_notebook(show_table=True, show_all=False)